# Generated by Django 5.2.12 on 2026-03-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_coordinator_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
